name: colon_proyect_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  image_picker: ^0.8.4+5
  path_provider: ^2.0.11
  flutter:
    sdk: flutter
  http: ^1.2.1
  html: ^0.15.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
